"""
CARLA Pre-Rendered Dataset Loader

Loads pre-rendered CARLA traffic sign images with YOLO-format annotations.
Provides the same interface as NuScenes2DDataset for seamless integration
with the adversarial robustness experiment pipeline.

Required directory structure:
    data/carla/
    ├-- metadata.json       # Dataset manifest (generated by carla_dataset_generator.py)
    ├-- clear/
    |   ├-- carla_clear_d05_y00_sign14.png
    |   ├-- carla_clear_d05_y00_sign14.txt   (YOLO: class cx cy w h)
    |   └-- ...
    ├-- rain/
    |   └-- ...
    └-- fog/
        └-- ...

Label format (YOLO):
    class_id  centre_x  centre_y  width  height
    (all normalised to [0, 1])
"""

import json
import os
import random
from typing import Dict, List, Optional, Tuple

import cv2
import numpy as np
import torch
from torch.utils.data import Dataset


class CARLADataset(Dataset):
    """
    PyTorch Dataset for pre-rendered CARLA traffic sign images.
    
    Loads images and YOLO-format annotations from the CARLA dataset,
    providing the same dict interface as NuScenes2DDataset for drop-in
    use with the existing experiment pipeline.
    
    Args:
        data_root (str): Path to the CARLA dataset root. Defaults to data/carla
                         relative to the project root.
        split (str): 'train', 'val', or 'test'. Default: 'val'.
                     Split ratios: 60% train / 20% val / 20% test.
        img_size (tuple): Output image resolution (W, H). Default: (640, 640).
        weather_filter (str or list): Filter by weather condition(s).
                                     e.g., 'clear' or ['clear', 'rain'].
        distance_filter (int or list): Filter by distance(s) in metres.
                                       e.g., 10 or [5, 10, 15].
        sign_filter (int or list): Filter by GTSRB sign class ID(s).
        transform: Optional albumentations transform pipeline.
        seed (int): Random seed for reproducible splits. Default: 42.
    """
    
    # Default path relative to project root
    DEFAULT_DATA_ROOT = os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        "data", "carla"
    )
    
    # GTSRB class names for the 5 sign types used in CARLA generation
    SIGN_CLASSES = {
        1: "speed_limit_30",
        2: "speed_limit_50",
        13: "yield",
        14: "stop",
        17: "no_entry",
    }
    
    # Mapping from GTSRB class IDs to sequential detection class IDs (0-indexed)
    # This is needed because the detection models expect contiguous class labels
    GTSRB_TO_DET_CLASS = {
        1: 0,    # speed_limit_30 -> class 0
        2: 1,    # speed_limit_50 -> class 1
        13: 2,   # yield -> class 2
        14: 3,   # stop -> class 3
        17: 4,   # no_entry -> class 4
    }
    
    # Reverse mapping
    DET_TO_GTSRB_CLASS = {v: k for k, v in GTSRB_TO_DET_CLASS.items()}
    
    def __init__(self, data_root=None, split="val", img_size=(640, 640),
                 weather_filter=None, distance_filter=None, sign_filter=None,
                 transform=None, seed=42):
        self.split = split.lower()
        self.img_size = img_size
        self.transform = transform
        self.seed = seed
        
        # Resolve data root
        if data_root is None:
            data_root = self.DEFAULT_DATA_ROOT
        self.data_root = data_root
        
        # Normalise filter params to lists
        self.weather_filter = self._to_list(weather_filter)
        self.distance_filter = self._to_list(distance_filter)
        self.sign_filter = self._to_list(sign_filter)
        
        # Load samples
        print(f"[CARLA Loader] Loading CARLA dataset from: {self.data_root}")
        self.all_samples = self._discover_samples()
        self.samples = self._apply_split(self.all_samples)
        
        # Stats
        n_weather = len(set(s['weather'] for s in self.samples))
        n_dist = len(set(s['distance'] for s in self.samples))
        n_signs = len(set(s['sign_id'] for s in self.samples))
        print(f"[CARLA Loader] {self.split} split: {len(self.samples)} samples "
              f"({n_weather} weather x {n_dist} distances x {n_signs} sign types)")
    
    @staticmethod
    def _to_list(val):
        """Convert scalar or None to list."""
        if val is None:
            return None
        if isinstance(val, (list, tuple)):
            return list(val)
        return [val]
    
    def _discover_samples(self):
        """
        Discover all image/label pairs in the dataset directory.
        
        Uses metadata.json if available, otherwise scans subdirectories.
        """
        samples = []
        
        # Try loading from metadata.json first
        manifest_path = os.path.join(self.data_root, "metadata.json")
        if os.path.exists(manifest_path):
            samples = self._load_from_manifest(manifest_path)
        else:
            samples = self._scan_directory()
        
        # Apply filters
        if self.weather_filter:
            samples = [s for s in samples if s['weather'] in self.weather_filter]
        if self.distance_filter:
            samples = [s for s in samples if s['distance'] in self.distance_filter]
        if self.sign_filter:
            samples = [s for s in samples if s['sign_id'] in self.sign_filter]
        
        if len(samples) == 0:
            raise ValueError(
                f"No CARLA samples found in {self.data_root} with filters: "
                f"weather={self.weather_filter}, distance={self.distance_filter}, "
                f"sign={self.sign_filter}"
            )
        
        return samples
    
    def _load_from_manifest(self, manifest_path):
        """Load sample metadata from the generated manifest file."""
        with open(manifest_path, 'r') as f:
            data = json.load(f)
        
        samples = []
        for frame in data.get('frames', []):
            weather = frame.get('weather', 'clear')
            weather_dir = os.path.join(self.data_root, weather)
            img_path = os.path.join(weather_dir, frame['filename'])
            lbl_path = os.path.join(weather_dir, frame['label_file'])
            
            if not os.path.exists(img_path):
                # Try flat directory
                img_path = os.path.join(self.data_root, frame['filename'])
                lbl_path = os.path.join(self.data_root, frame['label_file'])
            
            if os.path.exists(img_path):
                samples.append({
                    'img_path': img_path,
                    'lbl_path': lbl_path,
                    'weather': weather,
                    'distance': frame.get('distance_m', 10),
                    'yaw': frame.get('yaw_deg', 0),
                    'sign_id': frame.get('sign_id', frame.get('gtsrb_class', 0)),
                    'sign_name': frame.get('sign_name', 'unknown'),
                    'carla_domain': frame.get('carla_domain', True),
                })
        
        return samples
    
    def _scan_directory(self):
        """Scan the directory for image/label pairs when no manifest exists."""
        samples = []
        
        # Check for weather subdirectories or flat structure
        weather_dirs = ['clear', 'rain', 'fog']
        search_dirs = []
        
        for w in weather_dirs:
            w_dir = os.path.join(self.data_root, w)
            if os.path.isdir(w_dir):
                search_dirs.append((w_dir, w))
        
        # Also search root directory
        search_dirs.append((self.data_root, 'unknown'))
        
        for dir_path, weather in search_dirs:
            for fname in sorted(os.listdir(dir_path)):
                if not fname.endswith('.png') and not fname.endswith('.jpg'):
                    continue
                
                img_path = os.path.join(dir_path, fname)
                lbl_path = os.path.join(dir_path, fname.rsplit('.', 1)[0] + '.txt')
                
                if not os.path.exists(lbl_path):
                    continue
                
                # Parse metadata from filename: carla_{weather}_d{dist}_y{yaw}_sign{id}
                meta = self._parse_filename(fname)
                if weather == 'unknown' and meta.get('weather'):
                    weather = meta['weather']
                
                samples.append({
                    'img_path': img_path,
                    'lbl_path': lbl_path,
                    'weather': weather,
                    'distance': meta.get('distance', 10),
                    'yaw': meta.get('yaw', 0),
                    'sign_id': meta.get('sign_id', 0),
                    'sign_name': self.SIGN_CLASSES.get(
                        meta.get('sign_id', 0), 'unknown'),
                    'carla_domain': True,
                })
        
        return samples
    
    @staticmethod
    def _parse_filename(fname):
        """
        Parse metadata from CARLA filename convention.
        Expected: carla_{weather}_d{dist}_y{yaw}_sign{id}.png
        """
        meta = {}
        base = fname.rsplit('.', 1)[0]  # Remove extension
        parts = base.split('_')
        
        for part in parts:
            if part in ('clear', 'rain', 'fog'):
                meta['weather'] = part
            elif part.startswith('d') and part[1:].isdigit():
                meta['distance'] = int(part[1:])
            elif part.startswith('y') and part[1:].isdigit():
                meta['yaw'] = int(part[1:])
            elif part.startswith('sign') and part[4:].isdigit():
                meta['sign_id'] = int(part[4:])
        
        return meta
    
    def _apply_split(self, samples):
        """Split samples into train/val/test using deterministic shuffle."""
        rng = random.Random(self.seed)
        indices = list(range(len(samples)))
        rng.shuffle(indices)
        
        n = len(indices)
        n_train = int(0.6 * n)
        n_val = int(0.2 * n)
        
        if self.split == 'train':
            split_indices = indices[:n_train]
        elif self.split in ('val', 'validation'):
            split_indices = indices[n_train:n_train + n_val]
        elif self.split == 'test':
            split_indices = indices[n_train + n_val:]
        elif self.split == 'all':
            split_indices = indices
        else:
            raise ValueError(f"Unknown split: {self.split}. Use 'train'/'val'/'test'/'all'.")
        
        return [samples[i] for i in split_indices]
    
    def _parse_yolo_label(self, lbl_path):
        """
        Parse YOLO-format label file.
        
        Format: class_id centre_x centre_y width height (all normalised)
        
        Returns
        -------
        class_ids : list of int
        bboxes_xyxy : list of [x1, y1, x2, y2] (absolute pixel coordinates)
        """
        class_ids = []
        bboxes = []
        
        if not os.path.exists(lbl_path):
            return class_ids, bboxes
        
        with open(lbl_path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split()
                if len(parts) < 5:
                    continue
                
                cls = int(parts[0])
                cx = float(parts[1])
                cy = float(parts[2])
                w = float(parts[3])
                h = float(parts[4])
                
                # Convert normalised YOLO (cx, cy, w, h) to absolute (x1, y1, x2, y2)
                img_w, img_h = self.img_size
                x1 = (cx - w / 2) * img_w
                y1 = (cy - h / 2) * img_h
                x2 = (cx + w / 2) * img_w
                y2 = (cy + h / 2) * img_h
                
                # Clamp to image bounds
                x1 = max(0, min(x1, img_w))
                y1 = max(0, min(y1, img_h))
                x2 = max(0, min(x2, img_w))
                y2 = max(0, min(y2, img_h))
                
                if x2 > x1 and y2 > y1:
                    class_ids.append(cls)
                    bboxes.append([x1, y1, x2, y2])
        
        return class_ids, bboxes
    
    def __len__(self):
        return len(self.samples)
    
    def __getitem__(self, idx):
        """
        Load a single sample.
        
        Returns
        -------
        dict with keys:
            'image'    : torch.Tensor (3, H, W), float32, [0, 1]
            'bboxes'   : torch.Tensor (N, 4), float32, xyxy format
            'labels'   : torch.Tensor (N,), long
            'metadata' : dict with weather, distance, yaw, sign_type, etc.
        """
        sample_info = self.samples[idx]
        
        # Load image
        img = cv2.imread(sample_info['img_path'])
        if img is None:
            raise IOError(f"Failed to read image: {sample_info['img_path']}")
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        
        # Resize to target resolution
        img_resized = cv2.resize(img, self.img_size)
        
        # Apply optional transform
        if self.transform:
            transformed = self.transform(image=img_resized)
            img_resized = transformed['image']
        
        # Convert to tensor: (C, H, W), normalised to [0, 1]
        img_tensor = torch.from_numpy(img_resized).permute(2, 0, 1).float() / 255.0
        
        # Load YOLO labels
        class_ids, bboxes = self._parse_yolo_label(sample_info['lbl_path'])
        
        if len(bboxes) > 0:
            bboxes_tensor = torch.tensor(bboxes, dtype=torch.float32)
            # Use detection class IDs (0-indexed, contiguous)
            labels_tensor = torch.tensor(
                [self.GTSRB_TO_DET_CLASS.get(c, 0) for c in class_ids],
                dtype=torch.long
            )
        else:
            bboxes_tensor = torch.zeros((0, 4), dtype=torch.float32)
            labels_tensor = torch.zeros((0,), dtype=torch.long)
        
        metadata = {
            'weather': sample_info['weather'],
            'distance': sample_info['distance'],
            'yaw': sample_info['yaw'],
            'sign_id': sample_info['sign_id'],
            'sign_name': sample_info['sign_name'],
            'img_path': sample_info['img_path'],
            'carla_domain': sample_info.get('carla_domain', True),
        }
        
        return {
            'image': img_tensor,
            'bboxes': bboxes_tensor,
            'labels': labels_tensor,
            'metadata': metadata,
        }
    
    def get_weather_subsets(self):
        """
        Return separate CARLADataset instances filtered by weather.
        
        Returns
        -------
        dict : {weather_name: CARLADataset}
        """
        weathers = sorted(set(s['weather'] for s in self.all_samples))
        subsets = {}
        for w in weathers:
            subsets[w] = CARLADataset(
                data_root=self.data_root,
                split='all',
                img_size=self.img_size,
                weather_filter=w,
                transform=self.transform,
                seed=self.seed,
            )
        return subsets
    
    def get_distance_subsets(self):
        """
        Return separate CARLADataset instances filtered by distance.
        
        Returns
        -------
        dict : {distance_m: CARLADataset}
        """
        distances = sorted(set(s['distance'] for s in self.all_samples))
        subsets = {}
        for d in distances:
            subsets[d] = CARLADataset(
                data_root=self.data_root,
                split='all',
                img_size=self.img_size,
                distance_filter=d,
                transform=self.transform,
                seed=self.seed,
            )
        return subsets
    
    def get_class_distribution(self):
        """Return a dictionary mapping sign_id -> sample count."""
        dist = {}
        for s in self.samples:
            sid = s['sign_id']
            dist[sid] = dist.get(sid, 0) + 1
        return dict(sorted(dist.items()))
    
    def get_weather_distribution(self):
        """Return a dictionary mapping weather -> sample count."""
        dist = {}
        for s in self.samples:
            w = s['weather']
            dist[w] = dist.get(w, 0) + 1
        return dict(sorted(dist.items()))
    
    def get_distance_distribution(self):
        """Return a dictionary mapping distance_m -> sample count."""
        dist = {}
        for s in self.samples:
            d = s['distance']
            dist[d] = dist.get(d, 0) + 1
        return dict(sorted(dist.items()))


# =======================================================================
# DataLoader Builder (mirrors _build_nuscenes_dataloader in run_experiments.py)
# =======================================================================

def build_carla_dataloader(data_dir: str, split: str = "val", batch_size: int = 1,
                            weather_filter=None, distance_filter=None):
    """
    Build a DataLoader from the CARLA dataset.
    
    Returns images (B, 3, 640, 640) and a list of target dicts,
    matching the interface used by the nuScenes dataloader.
    
    Parameters
    ----------
    data_dir : str
        Path to the CARLA dataset root.
    split : str
        Dataset split: 'train', 'val', 'test', or 'all'.
    batch_size : int
        Batch size. Default: 1 (recommended for RTX 4050).
    weather_filter : str or list, optional
        Filter by weather condition(s).
    distance_filter : int or list, optional
        Filter by distance(s) in metres.
    
    Returns
    -------
    dataset : CARLADataset
    loader : DataLoader
    """
    from torch.utils.data import DataLoader
    
    dataset = CARLADataset(
        data_root=data_dir,
        split=split,
        weather_filter=weather_filter,
        distance_filter=distance_filter,
    )
    
    def collate_fn(batch):
        """Custom collate: stack images, collect targets as list of dicts."""
        images = torch.stack([s['image'] for s in batch])
        targets = []
        for s in batch:
            targets.append({
                'boxes': s['bboxes'],
                'labels': s['labels'],
            })
        return images, targets
    
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        collate_fn=collate_fn,
        drop_last=False,
    )
    
    return dataset, loader


# =======================================================================
# Self-Test
# =======================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("CARLADataset - Data Verification")
    print("=" * 60)
    
    try:
        dataset = CARLADataset(split="all")
        print(f"\n[ALL] Total samples: {len(dataset)}")
        
        # Distribution stats
        weather_dist = dataset.get_weather_distribution()
        distance_dist = dataset.get_distance_distribution()
        class_dist = dataset.get_class_distribution()
        
        print(f"\n[ALL] Weather distribution:")
        for w, c in weather_dist.items():
            print(f"  {w}: {c} samples")
        
        print(f"\n[ALL] Distance distribution:")
        for d, c in distance_dist.items():
            print(f"  {d}m: {c} samples")
        
        print(f"\n[ALL] Sign class distribution:")
        for s, c in class_dist.items():
            name = CARLADataset.SIGN_CLASSES.get(s, "unknown")
            print(f"  {s} ({name}): {c} samples")
        
        # Load a sample
        sample = dataset[0]
        print(f"\n[Sample 0]")
        print(f"  Image shape: {sample['image'].shape}")
        print(f"  Pixel range: [{sample['image'].min():.3f}, {sample['image'].max():.3f}]")
        print(f"  Bboxes: {sample['bboxes'].shape}")
        print(f"  Labels: {sample['labels']}")
        print(f"  Metadata: {sample['metadata']}")
        
        # Test splits
        for split in ['train', 'val', 'test']:
            ds = CARLADataset(split=split)
            print(f"\n[{split.upper()}] Samples: {len(ds)}")
        
        # Test DataLoader
        print(f"\n[DataLoader Test]")
        ds, loader = build_carla_dataloader(
            CARLADataset.DEFAULT_DATA_ROOT, split="val", batch_size=2
        )
        for images, targets in loader:
            print(f"  Batch images: {images.shape}")
            print(f"  Batch targets: {len(targets)} items")
            print(f"  Target[0] boxes: {targets[0]['boxes'].shape}")
            break
        
        print("\n" + "=" * 60)
        print("CARLA loader verification PASSED")
        print("=" * 60)
        
    except FileNotFoundError as e:
        print(f"\n[SKIP] {e}")
        print("Generate the dataset first:")
        print("  python src/data_prep/carla_dataset_generator.py --output data/carla")
    except ValueError as e:
        print(f"\n[SKIP] {e}")
        print("Generate the dataset first:")
        print("  python src/data_prep/carla_dataset_generator.py --output data/carla")
